# Generated by Django 5.2.3 on 2025-06-12 18:41

import dashboard.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', dashboard.models.UserManager()),
            ],
        ),
    ]
